name: 🐳 Publish Dockzero to Docker Hub

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            luizfgemi/dockzero:latest
            luizfgemi/dockzero:${{ github.ref_type == 'tag' && github.ref_name || 'main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify image
        run: docker buildx imagetools inspect luizfgemi/dockzero:latest
