name: Publish

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:

jobs:
  build-develop:
    name: Build develop image
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push develop image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            luizfgemi/dockzero:develop
            ghcr.io/luizfgemi/dockzero:develop
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    name: Build release image
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine new version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push release image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            luizfgemi/dockzero:latest
            luizfgemi/dockzero:${{ steps.tag_version.outputs.new_tag }}
            ghcr.io/luizfgemi/dockzero:latest
            ghcr.io/luizfgemi/dockzero:${{ steps.tag_version.outputs.new_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate changelog
        id: changelog
        run: |
          prev_tag="${{ steps.tag_version.outputs.previous_tag }}"
          git fetch --tags --force --prune
          echo "CHANGELOG<<EOF" >> "$GITHUB_ENV"
          if [ -n "$prev_tag" ]; then
            log=$(git log "${prev_tag}..HEAD" --pretty=format:"- %s")
            if [ -n "$log" ]; then
              printf '%s\n' "$log" >> "$GITHUB_ENV"
            else
              echo "No changes since ${prev_tag}" >> "$GITHUB_ENV"
            fi
          else
            echo "Initial release" >> "$GITHUB_ENV"
          fi
          echo "EOF" >> "$GITHUB_ENV"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Dockzero ${{ steps.tag_version.outputs.new_tag }}
          body: |
            Dockzero ${{ steps.tag_version.outputs.new_tag }}

            Minimal Docker dashboard — zero config, plug-and-play.

            Changes:
            ${{ env.CHANGELOG }}

            Docker Hub: https://hub.docker.com/r/luizfgemi/dockzero  
            GHCR: https://github.com/luizfgemi/dockzero/pkgs/container/dockzero
